import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import BlurBackground from "@/components/blurBackground";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Marczelloo.dev - Portfolio",
  description: "Generated by create next app",
};

// TODOLIST:
// - add live demo links to projects where applicable
// - optimize for mobile devices
// - build 404 page
// - add metadata tags for SEO and social media sharing
// - implement theme toggle (light/dark mode)
// - implement language switcher (PL/EN)
// - refine animations and transitions for better UX

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased grid grid-cols-[auto_1fr] h-screen`}>
        <Navbar />
        <main className="overflow-y-auto relative min-h-screen overflow-hidden pt-12 scroll-smooth">
          <BlurBackground />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
