import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import BlurBackground from "@/components/blurBackground";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased grid grid-cols-[auto_1fr] h-screen`}>
        <Navbar />
        <main className="overflow-y-auto relative min-h-screen overflow-hidden py-12 px-24">
          <BlurBackground />
          {children}
        </main>
      </body>
    </html>
  );
}
