import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { LayoutShell } from "./LayoutShell";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Marczelloo.dev - Portfolio",
  description: "Generated by create next app",
};

// TODOLIST:
// - add live demo links to projects where applicable
// - optimize for mobile devices
// - add metadata tags for SEO and social media sharing
// - implement theme toggle (light/dark mode)
// - implement language switcher (PL/EN)
// - refine animations and transitions for better UX

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} antialiased`}>
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
